### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by evman182**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/availity/availity-react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
5. Make sure your code passed the conventional commits check. Read more about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

### CODE REVIEW

**Review by jordan-a-young — APPROVED** [review]

**Comment by jordan-a-young** [comment]
It looks like the commit message check failed. For a docs change you should follow the format `docs: <commit message>`.

**Comment by evman182** [comment]
@jordan-a-young My bad. Fixed! Thanks!

**Review by jordan-a-young — APPROVED** [review]

**Comment by jordan-a-young** [comment]
Thanks for updating! Once the checks pass then you should be able to merge

**Comment by evman182** [comment]
I'm not a contributor on the repo, so someone else would have to merge :)

**Pull request merged**
