### PR TITLE
feat: add docusaurus docs

### PR DESCRIPTION
**Pull request by blockbat**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/availity/availity-react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
5. Make sure your code passed the conventional commits check. Read more about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

### CODE REVIEW

**Comment by jordan-a-young** [comment]
Does this change the Gatsby docs to use Docusaurus instead?

**Comment by blockbat** [comment]
Yep, we plan on deprecating the gatsby theme in favor of docusarus.

**Comment by robmcguinness** [comment]
Any chance we can get preview deployed somewhere?

**Comment by blockbat** [comment]
Sure, I'll work on that.

**Comment by chrishavekost** [comment]
Looks like there was a bad merge in `packages/mock/mock-requests`, will be fixing that.

**Review by jordan-a-young — APPROVED** [review]
Looks good!

**Pull request merged**
