### PR TITLE
Feat/hover styles all icons 2

### PR DESCRIPTION
**Pull request by stranzhay**
duplicate pull request from before. all icons need to have curosor: pointer on hover.

### CODE REVIEW

**Comment by availity-bot-cicd** [comment]
🚀 Netlify deployed **condescending-leavitt-66e607** as draft

https://61571d278cc55f0fd315669a--condescending-leavitt-66e607.netlify.app

**Comment by availity-bot-cicd** [comment]
🚀 Netlify deployed **condescending-leavitt-66e607** as draft

https://61571e8e088bc914bb2e2787--condescending-leavitt-66e607.netlify.app

**Comment by stranzhay** [comment]
commitlint is not running when i commit. all of my commit messages look correct now for packages. so I am not sure why they are still failing.

**Comment by availity-bot-cicd** [comment]
🚀 Netlify deployed **condescending-leavitt-66e607** as draft

https://61571f67e5a12d1457ffb116--condescending-leavitt-66e607.netlify.app

**Comment by availity-bot-cicd** [comment]
🚀 Netlify deployed **condescending-leavitt-66e607** as draft

https://61571fa010ac3e1461b0b21c--condescending-leavitt-66e607.netlify.app

**Comment by LauRoxx** [comment]
> commitlint is not running when i commit. all of my commit messages look correct now for packages. so I am not sure why they are still failing.

I may be wrong but I don't think scope is needed for docusaurus and storybook. I think the main issue is you have it scoped to 'dinosaurdocs' instead of 'docusaurus' 
https://github.com/Availity/availity-react/blob/314d2447a8de0279da0bb40439c040517bb9222a/lerna.json#L5

@jordan-a-young @chrishavekost

**Comment by chrishavekost** [comment]
> > commitlint is not running when i commit. all of my commit messages look correct now for packages. so I am not sure why they are still failing.
> 
> I may be wrong but I don't think scope is needed for docusaurus and storybook. I think the main issue is you have it scoped to 'dinosaurdocs' instead of 'docusaurus'
> 
> https://github.com/Availity/availity-react/blob/314d2447a8de0279da0bb40439c040517bb9222a/lerna.json#L5
> 
> @jordan-a-young @chrishavekost

It's actually the storybook commit causing the issue, it should be scoped to `react-storybook`
The workspace definitions reference the directories that contain workspaces, but the scopes we need to use come from the package names themselves
```
You have commit messages with errors

⧗   input: feat(storybook): adding style element to icon in storybook
✖   scope must be one of [dinosaurdocs, analytics, app-icon, authorize, avatar, breadcrumbs, date, favorites, feature, feedback, form-upload, form, help, hooks, icon, link, list-group-item, list-group, mock, page-header, pagination, payer-logo, phone, progress, reactstrap-validation-date, reactstrap-validation-select, select, spaces, step-wizard, training-link, typography, upload, react-storybook] [scope-enum]
```

**Comment by stranzhay** [comment]
@chrishavekost @LauRoxx ya i had already reverted those out and recommitted the correct ones and that still hasn't fixed it, its like it is still running on old commits

Screen Shot 2021-10-01 at 8 09 15 PM

**Pull request closed without merging**
