### PR TITLE
refactor(page-header): align feedback next to app name and bottom of …

### PR DESCRIPTION
**Pull request by chrishavekost**
…PageHeader

**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/availity/availity-react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
8. Make sure your code passed the conventional commits check. Read more about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

### CODE REVIEW

**Comment by GoPro16** [comment]
I think for some `PageHeader` usages the alignment of the feedback button is fine. But others like in the storybook example it looks a little off IMO.

**Comment by nylon22** [comment]
> I think for some `PageHeader` usages the alignment of the feedback button is fine. But others like in the storybook example it looks a little off IMO.

Agreed. Can we move the feedback button back over to the right of the header and next to the logo?

**Comment by adrian-santos** [comment]
Are we gonna move the `Feedback` button next to the `appName` starting on this version? I think it was okay when it was on the right side.

**Comment by chrishavekost** [comment]
> Are we gonna move the `Feedback` button next to the `appName` starting on this version? I think it was okay when it was on the right side.

After talking with Kyle and Tyson we decided the button will stay where it was (next to the payer logo) and just make a change to have it bottom-aligned. I'll have this PR updated today with the change.

**Comment by chrishavekost** [comment]
75f12db realigns feedback with payer logo. Uses `flex` for alignment and for keeping button size consistent (`flex-shrink-0`), also removes `float` property since it's ignored in a `flex` container.

**Review by GoPro16 — APPROVED** [review]
LGTM
https://i.imgur.com/Q3cUg29.gif

**Pull request merged**
