### PR TITLE
fix(payer-logo): correct path from payerID query

### PR DESCRIPTION
**Pull request by nylon22**

### CODE REVIEW

**Comment by GoPro16** [comment]
Can you write a quick unit test to make sure the logo is getting populated in the `<img /≥`. I ran the current test suite off master and they all succeed.

**Comment by nylon22** [comment]
that is because [the url it defaults to](https://github.com/Availity/availity-react/blob/master/packages/payer-logo/PayerLogo.js#L66) is the same as the [mocked resolved value](https://github.com/Availity/availity-react/blob/master/packages/payer-logo/tests/PayerLogo.test.js#L26) in the test.

I could change the resolved value and write an additional test checking both the default logic and the logic for handling if it gets a url back. that good? @GoPro16

**Comment by GoPro16** [comment]
Hmm, okay we should definitely change that then so we can create a unit test to make sure no future changes break this.

**Comment by GoPro16** [comment]
LGTM.

**Pull request merged**
