### PR TITLE
Fixes Typescript Definitions For Label Props

### LINKED ISSUE #279: AvSelectField | Label Ts Def Type should be of Type String or ReactType
https://github.com/Availity/availity-react/blob/720859d6e3569d8b5ea5918616bd07a7dfe04a3d/packages/reactstrap-validation-select/AvSelectField.d.ts#L2

### PR DESCRIPTION
**Pull request by GoPro16**
fixes #279

### CODE REVIEW

**Comment by jordan-a-young** [comment]
While we are updating types, can we allow the label prop to be a string or
a react component?

Not sure if these updates do that or not as my TypeScript is weak.

**Comment by GoPro16** [comment]
> While we are updating types, can we allow the label prop to be a string or a react component? Not sure if these updates do that or not as my TypeScript is weak.

Yeah its doing that. Essentially the `|` operator is an OR statement. So its `ReactType` or `String`

**Comment by djejaquino** [comment]
@chrishavekost Actually `React.ReactType` is parameterized with any type, which I believe is `props` definition. `React.ElementType` should be used instead though.

**Comment by GoPro16** [comment]
Correct way to do it is `React.ReactNode`.

https://codesandbox.io/s/still-cloud-c41j8

**Pull request merged**
