### PR TITLE
Fix/date range same day

### PR DESCRIPTION
**Pull request by nylon22**
for `date` and `reactstrap-validation-date`, allows the same day to be selected as the start and the end date by leveraging the `minimumNights` prop from `react-dates`.  In `date`, it is overridable due to `datepickerProps`.

### CODE REVIEW

**Comment by robmcguinness** [comment]
this should already be supported. @GoPro16 can you validate?

**Comment by jordan-a-young** [comment]
I tried the story book example earlier today, and it was not. I have also
experienced the bug in development.

**Comment by robmcguinness** [comment]
strange. one of the features request that was recently fixed was same day selection along with presets. I thought both were already solved.

**Comment by robmcguinness** [comment]
i remember now: the `ranges` had the ability to select same day which is not the same as this fix. 

image

mea culpa.

**Comment by robmcguinness** [comment]
i fixed the build previews. I think we are missing `minimumNights` from the knobs.

**Comment by GoPro16** [comment]
> i fixed the build previews. I think we are missing `minimumNights` from the knobs.

We can also include this in the knobs or just make a note about it since its just a date picker prop that we set the default use case for.

**Comment by adrian-santos** [comment]
Looks good. Thanks @nylon22

**Pull request merged**
