### PR TITLE
Feat/upload

### PR DESCRIPTION
**Pull request by dapatiga**
**Before submitting a pull request,** please make sure the following is done:

1. Fork [the repository](https://github.com/availity/availity-react) and create your branch from `master`.
2. Run `yarn` in the repository root.
3. If you've fixed a bug or added code that should be tested, add tests!
4. Ensure the test suite passes (`yarn test`). Tip: `yarn test --watch TestName` is helpful in development.
5. Make sure your code passed the conventional commits check. Read more about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/#summary)

### CODE REVIEW

**Comment by availity-bot-cicd** [comment]
🚀 Netlify deployed **condescending-leavitt-66e607** as draft

https://60e5b8a42c102383577cdf21--condescending-leavitt-66e607.netlify.app

**Comment by availity-bot-cicd** [comment]
🚀 Netlify deployed **condescending-leavitt-66e607** as draft

https://60e5e1ee8d7443b75e700b47--condescending-leavitt-66e607.netlify.app

**Comment by availity-bot-cicd** [comment]
🚀 Netlify deployed **condescending-leavitt-66e607** as draft

https://60e5e5e8e48305bb5f59b351--condescending-leavitt-66e607.netlify.app

**Comment by availity-bot-cicd** [comment]
🚀 Netlify deployed **condescending-leavitt-66e607** as draft

https://60e5ea23ce6669c6b2592aa4--condescending-leavitt-66e607.netlify.app

**Review by chrishavekost — APPROVED** [review]
Changes LGTM. Squashed the commits to keep the changlogs a little cleaner and noted a breaking change by requiring v4 of upload-core

**Comment by availity-bot-cicd** [comment]
🚀 Netlify deployed **condescending-leavitt-66e607** as draft

https://60e62495b5874408f3370e81--condescending-leavitt-66e607.netlify.app

**Pull request merged**
